---
name: Image builds

on:
  push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev
#   workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get -y update
          sudo apt-get -y install qemu-system-arm qemu-user-static binfmt-support bmap-tools kpartx packer

      - name: Run packer
        run: |
          sudo packer init builder/main.pkr.hcl
          sudo packer build builder/main.pkr.hcl
