---
name: Image builds

on:
  push:
#     branches:
#       - dev
#   pull_request:
#     branches:
#       - dev
#   workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get -y update
          sudo apt-get -y install qemu-system-arm qemu-user-static binfmt-support bmap-tools kpartx packer

      - name: Run packer
        run: |
          sudo packer init builder/main.pkr.hcl
          sudo packer build builder/main.pkr.hcl
          sudo mv output-raspbian/image photobooth-raspbian.img
          sudo sha256sum photobooth-raspbian.img > photobooth-raspbian.sha256
          sudo zip -s2g photobooth-raspbian.zip photobooth-raspbian.sha256 photobooth-raspbian.img
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "photobooth-raspbian.z*"
          body: foo
